version: '3.5'
services:
    frps:
        image: glzjin/frp:latest
        restart: always
        volumes:
            - ./frp:/etc/frp
        entrypoint:
            - /usr/local/bin/frps
            - -c
            - /etc/frp/frps.ini
        ports:
            - 80:80
            - "127.0.0.1:9004:8081"
            - "18800-19000:18800-19000"
        networks:
            default:
            frp:
                ipv4_address: 172.1.0.20

    frpc:
        image: glzjin/frp:latest
        restart: always
        volumes:
            - ./frp:/etc/frp
        depends_on:
            - frps
        entrypoint:
            - /usr/local/bin/frpc
            - -c
            - /etc/frp/frpc.ini
        networks:
            default:
            frp:
                ipv4_address: 172.1.0.10
            frp_containers:
        ports:
            - 9003:7400

networks:
    default:
    frp:
        driver: overlay
        internal: true
        ipam:
            config:
                - subnet: 172.1.0.0/16
    frp_containers:
        attachable: true
        driver: overlay
        internal: true
        ipam:
            config:
                - subnet: 172.2.0.0/16
